import { Professor } from "./types";

export const professors: Professor[] = [
  {
    id: "1",
    name: "Furong Huang",
    department: "Computer Science",
    university: "University of Maryland",
    researchTags: ["Large Language Models", "Federated Learning", "Trustworthy AI"],
    baseScore: 91,
    latestPaper: "FedAGM: Federated Learning with Adaptive Gradient Manipulation for Heterogeneous Data",
    paperAbstract:
      "We present FedAGM, a novel federated learning framework that addresses the statistical heterogeneity problem in distributed machine learning. Our approach uses adaptive gradient manipulation to align local model updates with the global objective, achieving state-of-the-art performance on non-IID data distributions while maintaining formal privacy guarantees under differential privacy constraints.",
    fundingStatus: "NSF Funded",
    email: "furongh@cs.umd.edu",
    initials: "FH",
    avatarColor: "#D85A30",
  },
  {
    id: "2",
    name: "Hal Daumé III",
    department: "CS & UMIACS",
    university: "University of Maryland",
    researchTags: ["Natural Language Processing", "Machine Learning", "AI Fairness"],
    baseScore: 85,
    latestPaper: "Calibrated Uncertainty in Language Models via Contrastive Decoding",
    paperAbstract:
      "Language models often produce overconfident outputs that fail to reflect genuine uncertainty in knowledge-intensive tasks. We introduce a contrastive decoding method that improves calibration by contrasting outputs from models with different knowledge levels, enabling more reliable uncertainty estimation without expensive sampling procedures.",
    fundingStatus: "NSF Funded",
    email: "hal@cs.umd.edu",
    initials: "HD",
    avatarColor: "#2563EB",
  },
  {
    id: "3",
    name: "Tom Goldstein",
    department: "Computer Science",
    university: "University of Maryland",
    researchTags: ["Computer Vision", "Adversarial ML", "Optimization"],
    baseScore: 78,
    latestPaper: "Adversarial Patches in the Wild: Evaluating Physical-World Attack Robustness at Scale",
    paperAbstract:
      "Physical adversarial patches pose a significant threat to vision systems deployed in the real world. We conduct the first large-scale empirical study of adversarial patches under natural environmental variations—lighting, angle, occlusion—and demonstrate that existing defenses degrade significantly under these conditions, motivating a new benchmark for robustness evaluation.",
    fundingStatus: "DARPA Funded",
    email: "tomg@cs.umd.edu",
    initials: "TG",
    avatarColor: "#7C3AED",
  },
  {
    id: "4",
    name: "John S. Baras",
    department: "ECE / ISR",
    university: "University of Maryland",
    researchTags: ["Multi-Agent Systems", "Networked Control", "Autonomous Systems"],
    baseScore: 72,
    latestPaper: "Trust Propagation in Multi-Agent Reinforcement Learning with Communication Constraints",
    paperAbstract:
      "We study the problem of building and propagating trust among agents in a multi-agent reinforcement learning framework where communication is unreliable and adversarial agents may exist. Our trust propagation algorithm allows honest agents to collaboratively identify and isolate malicious agents while achieving near-optimal cooperative performance.",
    fundingStatus: "DARPA Funded",
    email: "baras@umd.edu",
    initials: "JB",
    avatarColor: "#059669",
  },
  {
    id: "5",
    name: "Yiannis Aloimonos",
    department: "CS / UMIACS",
    university: "University of Maryland",
    researchTags: ["Computer Vision", "Robotics", "Active Perception"],
    baseScore: 76,
    latestPaper: "Language-Grounded Action Recognition for Robot Manipulation from Sparse Demonstrations",
    paperAbstract:
      "We present a framework that enables robots to recognize and replicate manipulation actions from as few as three human demonstrations by grounding action primitives in natural language descriptions. Our model learns compositional action representations that generalize across object categories and workspace configurations, significantly outperforming imitation learning baselines.",
    fundingStatus: "NSF Funded",
    email: "yiannis@cs.umd.edu",
    initials: "YA",
    avatarColor: "#DC2626",
  },
  {
    id: "6",
    name: "Marine Carpuat",
    department: "CS & UMIACS",
    university: "University of Maryland",
    researchTags: ["NLP", "Machine Translation", "Cross-lingual AI"],
    baseScore: 88,
    latestPaper: "Code-Switched Instruction Tuning: Teaching LLMs to Follow Commands in Mixed-Language Contexts",
    paperAbstract:
      "Multilingual users frequently switch between languages within a single utterance, yet instruction-tuned LLMs struggle to follow commands in code-switched contexts. We introduce CSInT, a dataset and fine-tuning methodology that improves instruction following in code-switched settings by 23% on average across 8 language pairs without degrading monolingual performance.",
    fundingStatus: "NSF Funded",
    email: "marine@cs.umd.edu",
    initials: "MC",
    avatarColor: "#D97706",
  },
];
